baseURL = 'https://dylanjroy.github.io/'
languageCode = 'en-us'
title = 'Dylan Joseph Roy-Leo'
theme = 'hugo-brewm'
[params]
    title = 'Dylan Joseph Roy-Leo'
    [params.logo]
        logoType = true
[taxonomies]
    stage = "stage"
    tag = "tags"
    category = "categories"
[[menu.main]]
    identifier = "github"
    name = "GitHub!"
    url = "https://github.com/dylroy"
    pre = "github"
[[menu.main]]
    identifier = "about"
    name = "All about me"
    pageRef = "/"
    [[menu.main]]
        identifier = "professional_about"
        name = "Professional"
        Post = "About my academic and professional career"
        parent = "about"
        pageRef = "/"
    [[menu.main]]
        identifier = "personal_about"
        name = "Personal"
        Post = "About my hobbies and wife"
        parent = "about"
        pageRef = "/posts/my-first-post.md"

[caches]
    [caches.images]
        dir = ':cacheDir/images'